### ISSUE TITLE
Error message using .summary()

### ISSUE THREAD

**Issue by dsrai** [svalkiers/clusTCR#31]
only happens when I use my own data but works with the given dataset.
It produces the initial output csv but doesn't show summary or features

>>> output.summary()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/____/miniconda3/lib/python3.9/site-packages/clustcr/clustering/clustering.py", line 32, in summary
    motifs = FeatureGenerator(self.clusters_df).clustermotif(cutoff=motif_cutoff)
  File "/home/_____/miniconda3/lib/python3.9/site-packages/clustcr/analysis/features.py", line 184, in clustermotif
    profile = profile_matrix(sequences)
  File "/home/______/miniconda3/lib/python3.9/site-packages/clustcr/analysis/tools.py", line 47, in profile_matrix
    profile[i][pos] = np.round(psc.loc[i] / len(sequences),2)
KeyError: '_'

>>> features = output.compute_features(compute_pgen=True)
/home/_____/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:380: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/home/____/miniconda3/lib/python3.9/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/____/miniconda3/lib/python3.9/site-packages/clustcr/clustering/clustering.py", line 49, in compute_features
    return FeatureGenerator(self.clusters_df).get_features(compute_pgen=compute_pgen)
  File "/home/_____/miniconda3/lib/python3.9/site-packages/clustcr/analysis/features.py", line 167, in get_features
    pchem = self._calc_physchem()
  File "/home/____/miniconda3/lib/python3.9/site-packages/clustcr/analysis/features.py", line 106, in _calc_physchem
    properties[prop].append(np.average([physchem_properties[prop][aa] for aa in seq]))
  File "/home/_____/miniconda3/lib/python3.9/site-packages/clustcr/analysis/features.py", line 106, in <listcomp>
    properties[prop].append(np.average([physchem_properties[prop][aa] for aa in seq]))
KeyError: '_'

Appreciate any help!

**Comment by MaxVanHoucke** [comment]
Hi there!

Thanks for letting us know about this error.
There might be some non amino-acid characters in your sequences such as an apostrophe causing the error.
Filtering out sequences that contain such characters before clustering should fix it.
If the issue persists, feel free to reach out again!

All the best
Max
